---
abstract: 'mapping ISO codes to localized country names'
author:
  - 'Bernhard Graf <graf@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Locale-Country-Multilingual
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Data::Inheritable: 0
  File::Spec: 0
  Symbol: 0
version: 0.22
